db_host: "localhost"  # IP address of the device hosting the MySQL database server
db_user: "YOUR_USERNAME"  # User name of the database server
db_password: "YOUR_PASSWORD" # Password for the database user
db_name: "IoTDatabase"  # Database to be accessed
db_port: 3306  # Port used by database
parent_dir_path: '/some/path/to/directory'  # Directory where csv files or subdirectories containing csv files are located
table_name: "PMonData" # Table to be written to
# ***IMPORTANT*** Data types should correspond to columns in the csv files being processed in the order they appear
datatypes: ['DATETIME(6)', 'CHAR(30)', 'FLOAT', 'FLOAT', 'FLOAT', 'FLOAT'] 
